添加了tool配置教程
saedrna/2019-FreshTutorial pull request #1
Opened 2019-09-06 13:51 UTC by lxr074

2019-09-06 16:11 UTC, saedrna requested changes

2019-09-06 16:11 UTC, saedrna commented on osketch-tutorial/oksetchpro_plugin_helloworld/tool_area.cpp
> +        double area=NUM2DBL(rb_area)*0.0254*0.0254;
我定义了一个 meter 2 inch 和 inch 2 meter 的值，你这个可能会产生微小差异

2019-09-06 16:13 UTC, saedrna commented
把cmake qt的那四个教程也更新下，一步步怎么做，写详细点

2019-09-06 16:26 UTC, lxr074 commented
收到




------------------ 原始邮件 ------------------
发件人: "Han Hu"<notifications@github.com>; 
发送时间: 2019年9月7日(星期六) 凌晨0:13
收件人: "saedrna/2019-FreshTutorial"<2019-FreshTutorial@noreply.github.com>; 
抄送: "Floyd"<490992572@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [saedrna/2019-FreshTutorial] 添加了tool配置教程 (#1)




把cmake qt的那四个教程也更新下，一步步怎么做，写详细点
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-09-10 12:31 UTC, saedrna requested changes

2019-09-10 12:31 UTC, saedrna commented on ReadMe.md
> +  - 查找 Qt 库<br>
markdown 不要有 <br>字符

2019-09-10 12:31 UTC, saedrna commented on ReadMe.md
> +  - 创建 UI 文件<br>
同上

2019-09-10 12:31 UTC, saedrna commented on ReadMe.md
> +  - 编辑 UI 代码<br>
同上

2019-09-10 12:31 UTC, saedrna commented on ReadMe.md
> +    这表示这个头文件在一个单独的编译中只被包含一次。<br>
同上

2019-09-10 12:31 UTC, saedrna commented on ReadMe.md
> +    编译通过，但是运行提示错误。此处是由于有一插件未自动拷贝所致。在所创建的 anaconda 环境的 plugins 下找到 platforms 插件复制到 s1-CreateADialog\build\RelWithDebInfo  路径下即可成功运行。运行结果如下，点击按钮，即可输出 Hello World 。
现在应该可自动复制，并且会生成一个 qt.conf 文件

2019-09-10 13:00 UTC, lxr074 commented on ReadMe.md
> +  - 查找 Qt 库<br>
您的意思是不要有那个换行符是吗

2019-09-11 03:03 UTC, merged